### ISSUE TITLE
error with Plot function

### ISSUE THREAD

**Issue by chaoshengt** [danjgale/brainplot#9]
When I run the code:
```python
from surfplot import Plot

p = Plot(surf_lh=lh, surf_rh=rh)
```
There are some errors:
`ValueError: Surface be a path-like string, an instance of BSPolyData, or None`

How to slove this? thank you :)

**Comment by danjgale** [comment]
Hi @chaoshengt, whare are your `lh` and `rh` variables? They should either be a file path of a valid surface file (e.g., a GIFTI) or a preloaded surface (i.e an instance of `BSPolyData`)
